# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: '**'
    tags: '*'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x         

    - name: Build InfoPanel
      run: |
        dotnet restore
        dotnet publish InfoPanel\InfoPanel.csproj -c Release -o "${{ github.workspace }}InfoPanel\bin\publish\win-x64" -r win-x64 --self-contained -p:PublishReadyToRun=true       

    - name: Install and Compile Inno Setup Installer
      shell: powershell
      run: |
        cd ${{ github.workspace }}\InnoSetup
        iscc "setup.iss"  
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: InfoPanel
        path:  "${{ github.workspace }}/build/"

    - name: Upload Artifact Setup
      uses: actions/upload-artifact@v4
      with:
        name: InfoPanel-Setup
        path:  "${{ github.workspace }}/InnoSetup/Output/InfoPanelSetup.exe"           

###################################
# Everything below is only for tagged Releases
# be sure to add this to force it to be for tags only
# if: startsWith(github.ref, 'refs/tags/')
##################################                      
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      id: upload-release-asset
      uses: ncipollo/release-action@v1
      with:        
        artifacts: ${{ github.workspace }}/InnoSetup/Output/InfoPanelSetup.exe
        generateReleaseNotes: true

